site_name: swiftwing-simulation-tutorial
site_url: https://SwiftWing001.github.io/swiftwing-simulation-tutorial/
theme:
  # name: material
  # name: rtd-dropdown
  name: readthedocs
site_dir: $READTHEDOCS_OUTPUT/html